import "./global.css"
import Navbar from "../components/organismos/Navbar"
import Skills from '../components/organismos/Skills';
import Experience from '../components/organismos/Experience';
import Education from '../components/organismos/Education';
import PersonInfo from "@/components/organismos/PersonInfo";
import ContactIcons from "@/components/moleculas/ContactIcons";
import Footer from "@/components/organismos/Footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      <Navbar></Navbar>
      <section>
        <h1></h1>
        <PersonInfo />
        <ContactIcons/>
        <Education />
        <Experience />
        <Footer/>
        
      </section>
      
    
        {children}
      </body>
    </html>
  )
}

